# SPDX-FileCopyrightText: 2026 Xiaoqiang <username_nullptr@163.com>
# SPDX-License-Identifier: MIT

set(ALTUN_INSTALL_CMAKEDIR
	"${CMAKE_INSTALL_LIBDIR}/cmake/${PRO_NAME}"
	CACHE STRING "Install path for ${PRO_NAME} CMake package files."
)
set(ALTUN_BUILD_LINUX OFF)

if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
	set(ALTUN_BUILD_LINUX ON)
endif ()

set(ALTUN_PACKAGE_NEEDS_CYCLONEDDS OFF)
set(ALTUN_PACKAGE_NEEDS_DBUS OFF)

set(ALTUN_PACKAGE_NEEDS_BLKID OFF)
set(ALTUN_PACKAGE_NEEDS_GPIOD OFF)

if (ALTUN_BUILD_STATIC)
	set(ALTUN_PACKAGE_NEEDS_CYCLONEDDS ${ALTUN_BUILD_SBUS_CYCLONE})
	set(ALTUN_PACKAGE_NEEDS_DBUS ${ALTUN_BUILD_SBUS_DBUS})
	set(ALTUN_PACKAGE_NEEDS_BLKID ${ALTUN_BUILD_LINUX})

	if (ALTUN_BUILD_LINUX AND ALTUN_GPIOD_FOUND)
		set(ALTUN_PACKAGE_NEEDS_GPIOD ON)
	endif ()
endif ()

configure_package_config_file (
	cmake/AltunConfig.cmake.in
	${CMAKE_CURRENT_BINARY_DIR}/AltunConfig.cmake
	INSTALL_DESTINATION ${ALTUN_INSTALL_CMAKEDIR}
)
write_basic_package_version_file (
	${CMAKE_CURRENT_BINARY_DIR}/AltunConfigVersion.cmake
	VERSION ${PROJECT_VERSION}
	COMPATIBILITY SameMinorVersion
)
install(EXPORT altunTargets
	FILE altunTargets.cmake
	NAMESPACE altun::
	DESTINATION ${ALTUN_INSTALL_CMAKEDIR}
)
install(FILES
	${CMAKE_CURRENT_BINARY_DIR}/AltunConfig.cmake
	${CMAKE_CURRENT_BINARY_DIR}/AltunConfigVersion.cmake
	DESTINATION ${ALTUN_INSTALL_CMAKEDIR}
)
