# SPDX-FileCopyrightText: 2026 Xiaoqiang <username_nullptr@163.com>
# SPDX-License-Identifier: MIT

set(LIBEMPP_INSTALL_CMAKEDIR
	"${CMAKE_INSTALL_LIBDIR}/cmake/${PRO_NAME}"
	CACHE STRING "Install path for ${PRO_NAME} CMake package files."
)
set(LIBEMPP_BUILD_LINUX OFF)

if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
	set(LIBEMPP_BUILD_LINUX ON)
endif ()

set(LIBEMPP_PACKAGE_NEEDS_CYCLONEDDS OFF)
set(LIBEMPP_PACKAGE_NEEDS_DBUS OFF)

set(LIBEMPP_PACKAGE_NEEDS_BLKID OFF)
set(LIBEMPP_PACKAGE_NEEDS_GPIOD OFF)

if (LIBEMPP_BUILD_STATIC)
	set(LIBEMPP_PACKAGE_NEEDS_CYCLONEDDS ${LIBEMPP_BUILD_SBUS_CYCLONE})
	set(LIBEMPP_PACKAGE_NEEDS_DBUS ${LIBEMPP_BUILD_SBUS_DBUS})
	set(LIBEMPP_PACKAGE_NEEDS_BLKID ${LIBEMPP_BUILD_LINUX})

	if (LIBEMPP_BUILD_LINUX AND LIBEMPP_GPIOD_FOUND)
		set(LIBEMPP_PACKAGE_NEEDS_GPIOD ON)
	endif ()
endif ()

configure_package_config_file (
	cmake/libEMppConfig.cmake.in
	${CMAKE_CURRENT_BINARY_DIR}/libEMppConfig.cmake
	INSTALL_DESTINATION ${LIBEMPP_INSTALL_CMAKEDIR}
)
write_basic_package_version_file (
	${CMAKE_CURRENT_BINARY_DIR}/libEMppConfigVersion.cmake
	VERSION ${PROJECT_VERSION}
	COMPATIBILITY SameMinorVersion
)
install(EXPORT libEMppTargets
	FILE libEMppTargets.cmake
	NAMESPACE libEMpp::
	DESTINATION ${LIBEMPP_INSTALL_CMAKEDIR}
)
install(FILES
	${CMAKE_CURRENT_BINARY_DIR}/libEMppConfig.cmake
	${CMAKE_CURRENT_BINARY_DIR}/libEMppConfigVersion.cmake
	DESTINATION ${LIBEMPP_INSTALL_CMAKEDIR}
)
